version: '3.8'

services:
  jacuzzi2mqtt:
    build: .
    container_name: Jacuzzi2MQTT
    volumes:
      - .:/app
    working_dir: /app/spa2mqtt
    command: python -h
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: on-failure
