version: "3.8"

services:
  spa2mqtt:
    build: .
    container_name: spa2mqtt
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - VARIANT_DEFINITION=${VARIANT_DEFINITION}
      - SPA_IP=${SPA_IP}
      - SPA_PORT=${SPA_PORT}